http:
  port: "8081"
  
sfdc:
  username: "freddythomas@gmail.com"
  password: "Freddybechu7&"
  token: "WiHBCkzidDBkh0zZgm8csxMIj"
  
file:
  accountsDir: "C:/Users/007fr/Downloads/APDevFundamentals4.3_studentFiles_30oct2020/APDevFundamentals4.3_studentFiles_30oct2020/resources"
  
db:
  host: "iltdb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"